version: '3'

services:
  session-tut:
    container_name: session_boi
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/session-app
    ports:
      - '8080:8080'
    command: python3 src/main.py
