version: '3'

services:
  session-tut:
    container_name: session_boi
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/session-app
    ports:
      - '8000:8000'
    command: python3 src/main.py
