version: '3'

services:
  python-boi:
    build: 
      context: .
      dockerfile: Dockerfile_python
    volumes:
      - ./python-app:/python-app
    working_dir: /python-app
    ports: 
      - 3000:3000
    networks:
      - proxy-net
    command: python3 server.py

  node-boi:
    build: 
      context: .
      dockerfile: Dockerfile_node
    volumes:
      - ./node-app:/node-app
      - /node-app/node_modules
    working_dir: /node-app
    ports: 
      - 8000:8000
    networks: 
      - proxy-net
    command: node server.js
    
  nginx:
    build:
      context: .
      dockerfile: Dockerfile_nginx 
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports: 
      - 80:80
      - 443:443
    networks:
      - proxy-net
networks:
  proxy-net: