version: '3'

services:
  gopi:
    build:
      context: .
      dockerfile: Dockerfile
    volumes: 
      - .:/gopi
    ports: 
      - '8080:8080'
    environment:
      - GO111MODULE=on
    command: go run api.go